config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, :controllers => {registrations: 'registrations'}
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :assign_name

  has_many :books

  def full_name
  	self.first_name && self.last_name ? "#{self.first_name} #{self.last_name}" : "#{self.email}"
  end

  def assign_name
  	self.name = "#{self.first_name} #{self.last_name}"
  end
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
	self.table_name = "authors_books"
end

app/models/book.rb
class Book < ApplicationRecord

	has_and_belongs_to_many :authors

	validates_presence_of :title, :author_ids

	validates_uniqueness_of :title, {
		scope: :author_id,
		message: "you can't have two books with the same title"
	}

	def self.by_name(author_id)
		joins("join authors_books a on a.book_id = books.id").where("a.author_id = ?", author_id)
	end

	def print_citation
		if self.type_of_book == 'Print'
			"#{authors.map{|a| a.name.split(' ').reverse.join(' ')}.join(', ')}. <em>#{title}</em>. 
			#{ city.present? ? "#{city}:" : ""} #{ publisher.present? ? "#{publisher}," : "" } 
			#{ year_published.present? ? "#{year_published.year}." : ""} Print."
		end
	end

	def online_citation
		if self.type_of_book == 'Online book'
			"#{authors.map{|a| a.name.split(' ').reverse.join(' ')}.join(', ')}. <em>#{title}</em>.
			#{ city.present? ? "#{city}:" : ""} #{ publisher.present? ? "#{publisher}," : "" }
			#{ year_published.present? ? "#{year_published.year}." : ""} #{ website_title.present? ? "<em>#{website_title}.</em>" : ""}
			Web. #{ accessed_date.present? ? "#{accessed_date.day} #{Date::MONTHNAMES[accessed_date.month].slice(0,3)}. #{accessed_date.year}." : ""}"
		end
	end

	def database_citation
		if self.type_of_book == 'Database book'
			"#{authors.map{|a| a.name.split(' ').reverse.join(' ')}.join(', ')}. <em>#{title}</em>.
			#{ city.present? ? "#{city}:" : ""} #{ publisher.present? ? "#{publisher}," : "" }
			#{ year_published.present? ? "#{year_published.year}." : ""} #{ database_name.present? ? "<em>#{database_name}.</em>" : ""}
			Web. #{ accessed_date.present? ? "#{accessed_date.day} #{Date::MONTHNAMES[accessed_date.month].slice(0,3)}. #{accessed_date.year}." : ""}"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]
  before_action :authenticate_author!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authors_only, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:author_id].present?
      @books = Book.by_name(params[:author_id])
    else
      @books = Book.all
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :city, :publisher, :year_published, :type_of_book, :website_title, :database_name, :accessed_date, :author_ids => [])
    end

    def authors_only
      @book = Book.find(params[:id])
      if !@book.authors.include?(current_author)
        redirect_to books_path, alert: "You don't have access to this action"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:author).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:author).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<style>
  .book_website_title, .book_database_name, .book_accessed_date
  {
    display: none;
  }
</style>

<script>
  $(document).ready(function() {
    if($('#book_type_of_book').val() == "Online book"){
      $(".book_website_title").show();
      $(".book_accessed_date").show();
    }

    if($('#book_type_of_book').val() == "Database book"){
      $(".book_database_name").show();
      $(".book_accessed_date").show();
    }

  $('#book_type_of_book').change(function() {
      if ($(this).val() == "Online book"){
        $(".book_website_title").show();
      }
      else{
        $(".book_website_title").hide();
      }
  });

  $('#book_type_of_book').change(function() {
      if ($(this).val() == "Database book"){
        $(".book_database_name").show();
      }
      else{
        $(".book_database_name").hide();
      }
  });

  $('#book_type_of_book').change(function() {
      if ($(this).val() == "Online book" || $(this).val() == "Database book"){
        $(".book_accessed_date").show();
      }
      else{
        $(".book_accessed_date").hide();
      }
  });
  });
</script>

<%= simple_form_for(@book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :title, label: 'Title' %>
  </div>

  <div class="field">
    <%= form.association :authors, label: 'Author(s)' %>
  </div>

  Need to create a citation for your book? Fill in details below:

  <div class="field">
    <%= form.input :city, label: 'City' %>
  </div>

  <div class="field">
    <%= form.input :publisher, label: 'Publisher' %>
  </div>

  <div class="field">
    <%= form.input :year_published, label: 'Year Published', as: :date, start_year: Date.today.year - 90, end_year: Date.today.year, discard_day: true, discard_month: true, include_blank: true %>
  </div>

  <div class="field">
    <%= form.input :type_of_book, label: 'Type of book', collection: ([['Print', 'Print'], ['Online book', 'Online book'], ['Book from a Database', 'Database book']]) %>
  </div>

  <div class="field">
    <%= form.input :website_title, label: 'Website title' %>
  </div>

  <div class="field">
    <%= form.input :database_name, label: 'Database name' %>
  </div>

  <div class="field">
    <%= form.input :accessed_date, label: 'Date accessed', include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<div class="field">
  <%= form_tag({controller: "books", action: "index"}, method: "get") do %>
    <% @options = Author.all.map { |a| [ a.full_name, a.id ] } %>
    Please select an author&nbsp;&nbsp;<%= select_tag(:author_id, options_for_select(@options), :prompt => "All authors") %>
    <input type="submit" value="Filter" form_class = "btn-form" class = "btn btn-default btn-form" />
  <%end%>
</div>
<hr>
<table class="hoverTable">
  <thead>
    <tr align="left">
      <th>Title</th>
      <th>Author(s)</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr align="left">
        <td><%= book.title %></td>
        <td><%= book.authors.map{|a| a.name}.join(', ') %></td>
        <td><%= link_to 'Show', book %></td>
        <% if book.authors.include?(current_author) %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author(s):</strong>
  <%= @book.authors.map{|a| a.name}.join(', ') %>
</p>

<% if @book.print_citation.present? %>
<p>
  <strong>Citation:</strong>
  <%= sanitize @book.print_citation %>
</p>
<%end%>

<% if @book.online_citation.present? %>
<p>
  <strong>Citation:</strong>
  <%= sanitize @book.online_citation %>
</p>
<%end%>

<% if @book.database_citation.present? %>
<p>
  <strong>Citation:</strong>
  <%= sanitize @book.database_citation %>
</p>
<%end%>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="header">
      <ul>
        <li style="float: left;"><a href="/">Rails Bookshelf</a></li>
        <% if author_signed_in? %>
          <li><%= link_to 'Logout', destroy_author_session_path, method: :delete %></li>
          <li><%= link_to current_author.first_name, edit_author_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_author_registration_path %></li>
          <li><%= link_to 'Sign in', new_author_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookshelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
	<%= render 'layouts/header' %>
  </header>

<% if notice %><p class="alert alert-info"><%= notice %></p><% end %>
<% if alert %><p class="alert alert-warning"><%= alert %></p><% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Test bookshelf -- home for all books</h1>

<h1><%= link_to "All Books", books_path %></h1>
<% if author_signed_in? %>
	<h1><%= link_to "My Books", books_path(:author_id => current_author.id) %></h1>
<%end%>